### ISSUE TITLE
PostgreSQL Major: "OLE DB or ODBC error: [Expression.Error] We couldn't fold the expression to the data source. Please try a simpler expression.."

### ISSUE THREAD

**Issue by sgoley** [sgoley/DirectQuery-for-ODBC-in-PowerBI#1]
![image](https://user-images.githubusercontent.com/10283176/55345339-a48f2300-547d-11e9-8356-0a49874581e3.png)

**Comment by sgoley** [comment]
Four common folding errors:

1)
"Data Type of column order_status with searchable property UNSEARCHABLE should be SEARCHABLE or ALL_EXCEPT_LIKE." = Text column not being recognized as searchable (One of my proprietary text columns which didn't get correctly cast to WLONGVARCHAR) (ex. sort functions)

2)
"This ODBC driver doesn't support SQL_FN_TD_TIMESTAMPDIFF. You can override this by using SqlGetInfo for SQL_TIMEDATE_FUNCTIONS." = Date column that is being cast to Timestamp for an odd reason and so Date math cannot be applied. (ex. date filters)

3)
"This ODBC Driver does not support SQL_GB_NO_RELATION. You can override this by using SqlCapabilities" = Driver does not support the highest level of Group By Requirements, has to be set in custom driver as another one of these values:
SQL_GB_NOT_SUPPORTED = 0,
SQL_GB_GROUP_BY_EQUALS_SELECT = 1,
SQL_GB_GROUP_BY_CONTAINS_SELECT = 2,
SQL_GB_NO_RELATION = 3,
SQL_GB_COLLATE = 4
(ex. group numeric by name)

4)
"This ODBC driver doesn't support SQL_AF_SUM. You can override this by using SqlGetInfo for SQL_AGGREGATE_FUNCTIONS" = Flag not set to allow standard aggregate functions / not picked up in Sql92Conformity parameter. 
(ex. any numeric "default summarizations")

Currently 1 & 2 are outstanding.

**Comment by sgoley** [comment]
5. Text search on directquery does not work. 

Make a slicer which has a text search function based on a field in a directquery table and then search for values:

![image](https://user-images.githubusercontent.com/10283176/56061867-ad62dd00-5d38-11e9-9821-d691e819e99a.png)

**Comment by Commit-Data-BI-Team** [comment]
@sgoley hey, 
first of all, thank you for you hard work.

im trying to understand how to resolve the "try simpler expression" but i dont know how. 

is that fixable at all? 

thanks

**Comment by sgoley** [comment]
@dr0rRvali Oh no problem! I just realized how needed it was after I found there really was no answer on this available. 

For your situation - would you mind answering a few questions?
* What database and odbc driver + version are you using?
* what's the data type on the field that you're working with? 
* what visual are you using?

**Comment by Commit-Data-BI-Team** [comment]
@sgoley 

sure, thank you for your answer!!

Database: MySql Community Edition
ODBC Driver: MySql ODBC 8.0 Unicode Driver
DataType Field: Int 
Visual: Table

Decsription: when i drag the int column it is ok (but it is sum aggregated by deafult), but when i check the "dont summerize" in power bi i get that error. 

i cant see anything that is not aggregated.

**Comment by sgoley** [comment]
@dr0rRvali, 

Ok this existing version is currently focused on PostgreSQL. There was someone else who contacted me about a similar issue using SQL Server and we had to make a fork of the project to handle some of those cases. I'm guessing this is going to be similar for MySQL. Does the existing MySQL integration not support DirectQuery?

I won't promise anything but I'll move this to a new issue for MySQL compatibility.

**Comment by Commit-Data-BI-Team** [comment]
@sgoley you are right.
the existing mysql integration is not supporting direct query (why did he want this to sql if it is supported for DC?? out of curiosity)  

it will be great if you can figure this out, also - it is for my client

**Comment by sgoley** [comment]
@dr0rRvali 

Sure - please contact me directly via email and we'll discuss the options from there.

**Comment by Commit-Data-BI-Team** [comment]
@sgoley sent you a LinkedIn request.

**Comment by sgoley** [comment]
> 
> 
> Four common folding errors:
> 
> 
> "Data Type of column order_status with searchable property UNSEARCHABLE should be SEARCHABLE or ALL_EXCEPT_LIKE." = Text column not being recognized as searchable (One of my proprietary text columns which didn't get correctly cast to WLONGVARCHAR) (ex. sort functions)
> 
> 
> "This ODBC driver doesn't support SQL_FN_TD_TIMESTAMPDIFF. You can override this by using SqlGetInfo for SQL_TIMEDATE_FUNCTIONS." = Date column that is being cast to Timestamp for an odd reason and so Date math cannot be applied. (ex. date filters)
> 
> 
> "This ODBC Driver does not support SQL_GB_NO_RELATION. You can override this by using SqlCapabilities" = Driver does not support the highest level of Group By Requirements, has to be set in custom driver as another one of these values:
> SQL_GB_NOT_SUPPORTED = 0,
> SQL_GB_GROUP_BY_EQUALS_SELECT = 1,
> SQL_GB_GROUP_BY_CONTAINS_SELECT = 2,
> SQL_GB_NO_RELATION = 3,
> SQL_GB_COLLATE = 4
> (ex. group numeric by name)
> 
> 
> "This ODBC driver doesn't support SQL_AF_SUM. You can override this by using SqlGetInfo for SQL_AGGREGATE_FUNCTIONS" = Flag not set to allow standard aggregate functions / not picked up in Sql92Conformity parameter.
> (ex. any numeric "default summarizations")
> 
> Currently 1 & 2 are outstanding.

1 & 2 have been resolved - now working on the date / time intervals operators (ex. SQL_TSI_DAY) for the datetimeadd and datetimediff functions.

**Comment by sgoley** [comment]
Closing to continue working on Datetime / Date interval function under separate issue:
#8

**Comment by newuser-dotcom** [comment]
Connecting PowerBI through Snowflake , and getting below error.

Using Direct Query

![Screenshot 2022-02-07 162256](https://user-images.githubusercontent.com/60541065/153125983-ba5174cc-bbca-4cc3-8bda-9265de4559f2.png)

**Comment by Mauricioortubeyz** [comment]
> Connecting PowerBI through Snowflake , and getting below error.
> 
> Using Direct Query
> 
> ![Screenshot 2022-02-07 162256](https://user-images.githubusercontent.com/60541065/153125983-ba5174cc-bbca-4cc3-8bda-9265de4559f2.png)

Set [enablefolding]= False
