### ISSUE TITLE
PostgreSQL Bug - new mashup engine breaks directquery connector

### ISSUE THREAD

**Issue by sgoley** [sgoley/DirectQuery-for-ODBC-in-PowerBI#10]
Tracking a new issue where Custom Connector works correctly with old reports (regardless of PowerBI application version) but not with newly created reports. 

### Reproduce steps:
- Create an ODBC Data Source (64bit) as normal. 
- Add Custom Connector .mez file to `Documents\Power BI Desktop\Custom Connectors` as normal
- Create new PowerBI Report
- Create new blank query
- Copy contents of M source language from old, working report into new query through advanced query. 

> `let
>     Source = ODBCPostgresDirect.Database("Retro SF PG"),
>     account_salesforce_d8b832js2t307u = Source{[Item="account",Schema="salesforce",Catalog="d8b832js2t307u"]}[Data]
> in
>     account_salesforce_d8b832js2t307u`

- Observe that preview correctly loads data for preview in Power Query Editor. 
![image](https://user-images.githubusercontent.com/10283176/83640029-90f7b480-a579-11ea-9057-37cbb415100f.png)

- Close and apply query changes.
- Resulting bug:
![old pbix vs new pbix](https://user-images.githubusercontent.com/10283176/83639068-242fea80-a578-11ea-819d-d90f51d0a89f.png)

**Comment by CurtHagenlocher** [comment]
What version of Power BI Desktop are you running? You can get this from the Diagnostics tab under File | Options and Settings | Options.

**Comment by CurtHagenlocher** [comment]
Well, apparently I fail again at reading comprehension -- sorry!

**Comment by mekam14** [comment]
Do you know if you have enabled the ["Enhanced dataset metadata" preview feature](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata ) in Power BI Desktop? Custom connectors aren't supported with that feature yet (they will in the June 2020 release of PBI Desktop). If you have this enabled then PBI Desktop will try to upgrade your reports on open, but if it identifies that it has custom connectors then it will fallback to the old format, but new reports would already be in the new format. This would explain why your existing pbix files still work, but copying the same queries to a blank report does not. If you do have it enabled, then please try disabling the preview feature, restarting PBI Desktop, and trying again. As I said, the next release of PBI Desktop will have support for custom connectors.

**Comment by sgoley** [comment]
@mekam14 
This is it! Thank you for the quick response - it looks like the enhanced dataset metadata preview feature was the culprit.

![image](https://user-images.githubusercontent.com/10283176/83775610-274cd880-a655-11ea-9f11-acec675d51d5.png)

Looking forward to that release very much now!
